<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>me.adeptr</groupId>
	<artifactId>adep-sk</artifactId>
	<version>1.0.0</version>
	<name>AdepSK</name>

	<properties>
		<java.version>1.8</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<licenses>
		<license>
			<name>GNU General Public License v3</name>
			<url>https://www.gnu.org/licenses/gpl-3.0.en.html</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Despical</name>
			<url>https://www.spigotmc.org/members/615094/</url>
			<roles>
				<role>developer</role>
			</roles>
		</developer>
	</developers>

	<repositories>
		<repository>
			<id>papermc</id>
			<url>https://papermc.io/repo/repository/maven-public/</url>
		</repository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/groups/public/</url>
		</repository>
		<repository>
			<id>elMakers</id>
			<url>http://maven.elmakers.com/repository/</url>
		</repository>
		<repository>
			<id>codemc-repo</id>
			<url>https://repo.codemc.org/repository/maven-public/</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>spigot-repo</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
		</repository>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
		<repository>
			<id>md5</id>
			<url>http://repo.md-5.net/content/groups/public</url>
		</repository>
		<repository>
			<id>MVM</id>
			<url>https://mvnrepository.com/artifact/com.oracle.ojdbc/ojdbc8</url>
		</repository>
		<repository>
			<id>placeholderapi</id>
			<url>http://repo.extendedclip.com/content/repositories/placeholderapi/</url>
		</repository>
		<repository>
			<id>dmulloy2-repo</id>
			<url>https://repo.dmulloy2.net/nexus/repository/public/</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>com.github.SkriptLang</groupId>
			<artifactId>Skript</artifactId>
			<version>dev36</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.github.paperspigot</groupId>
			<artifactId>paperspigot-api</artifactId>
			<version>1.8.8-R0.1-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.spigotmc</groupId>
			<artifactId>spigot-api</artifactId>
			<version>1.8.8-R0.1-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.spigotmc</groupId>
			<artifactId>spigot</artifactId>
			<version>1.8.8-R0.1-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fr.mrmicky</groupId>
			<artifactId>FastInv</artifactId>
			<version>3.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>me.clip</groupId>
			<artifactId>placeholderapi</artifactId>
			<version>2.9.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>net.jitse</groupId>
			<artifactId>npclib-plugin</artifactId>
			<version>2.7.1-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>fr.mrmicky</groupId>
			<artifactId>FastBoard</artifactId>
			<version>1.1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.WesJD.AnvilGUI</groupId>
			<artifactId>anvilgui</artifactId>
			<version>e6a8dbe196</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.ShaneBeee</groupId>
			<artifactId>SkBee</artifactId>
			<version>1.4.6</version>
		</dependency>
		<dependency>
			<groupId>fr.mrmicky</groupId>
			<artifactId>FastParticles</artifactId>
			<version>1.2.3</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.gmail.filoghost</groupId>
			<artifactId>holographicdisplays</artifactId>
			<version>2.3.2</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/lib/HolographicDisplays.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>3.3.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.mifmif</groupId>
			<artifactId>generex</artifactId>
			<version>1.0.2</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.30</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>org.eclipse.jdt.annotation</artifactId>
			<version>1.1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.comphenix.protocol</groupId>
			<artifactId>ProtocolLib</artifactId>
			<version>4.5.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>me.robin</groupId>
			<artifactId>leaderheads</artifactId>
			<version>1.0.0</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/lib/CorpseReborn.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>com.github.Despical</groupId>
			<artifactId>Commons-Box</artifactId>
			<version>1.1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.codemc.worldguardwrapper</groupId>
			<artifactId>worldguardwrapper</artifactId>
			<version>1.1.6-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<goals>
					<goal>compile</goal>
				</goals>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.1.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<relocations>
								<relocation>
									<pattern>com.zaxxer.hikari</pattern>
									<shadedPattern>me.adeptr.adepsk.database.hikari</shadedPattern>
								</relocation>
								<relocation>
									<pattern>de.tr7zw.changeme.nbtapi</pattern>
									<shadedPattern>me.adeptr.adepsk.nbt.nbtapi</shadedPattern>
								</relocation>
							</relocations>
							<createDependencyReducedPom>false</createDependencyReducedPom>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>